#!/usr/bin/python3
 
import os
from sys import argv , exit
import signal 

DEFAULT_FILE_MANAGER = "thunar"
DEFAULT_TERMINAL = "xfce4-terminal"
THEME = "/home/rupam/scripts/ribbon_bottom.rasi"
CLIPBOARD = ""
current = os.getcwd()
while True:
    option = os.popen(f"ls {current} | rofi -dmenu -theme {THEME} -p 'rofi-fm@({current})'").read().strip("\n")
    if option == '':
        exit()
    path = current + "/" + option 
    files  = os.path.isfile(path)

    folder = os.path.isdir(path)
    if files or folder:
        choices = '\n'.join(['open' , 'copy' , 'rename' , 'delete' , 'cut'])
        option1 = os.popen(f'echo "{choices}" | rofi -dmenu -theme /home/rupam/scripts/ribbon_bottom.rasi').read().strip("\n")
        if option1 == '':
            exit() 
        elif option1 == 'open':
            if files:
                os.system(f'xdg-open "{path}"')
            elif folder:
                current = path
                continue

        elif option1 == 'copy':

            CLIPBOARD = "copy " + path 
        elif option1 == 'rename':
            pass
        elif option1 == 'delete':
            os.remove(path)
        elif option1 == 'cut' : 
            CLIPBOARD = "cut " + path

    else:
        commands = [':fm' , ':q' , ':term' , ':paste' , ':b']
        option = option.split(" ")
        if option[0] in commands: 
            if option[0] == ':q':
                exit()
            elif option[0] == ':fm':
                os.system(f'{DEFAULT_FILE_MANAGER} {current}')
                exit()

            elif option[0] == ':term':
                os.system(f'{DEFAULT_TERMINAL} --working-directory={current}')
                exit()

            elif option[0] == ':paste':
                import shutil
                
                CLIPBOARD = CLIPBOARD.split()
                n = len(CLIPBOARD)
                if CLIPBOARD[0] == 'copy':
                    CLIPBOARD = ' '.join(CLIPBOARD[1:n])
                    old = CLIPBOARD
                    CLIPBOARD = CLIPBOARD.split('/')
                    n = len(CLIPBOARD)
                    new = current + "/" + CLIPBOARD[(n-1)]
                    shutil.copy(old ,new)
            
                elif CLIPBOARD[0] == 'cut':
                    CLIPBOARD = ' '.join(CLIPBOARD[1:n])
                    old = CLIPBOARD
                    CLIPBOARD = CLIPBOARD.split('/')
                    n = len(CLIPBOARD)
                    new = current + "/" + CLIPBOARD[(n-1)]
                    shutil.copy(old ,new)
                    os.remove(old)


            elif option[0] == ':b':
                parts = current.split("/")
                current =  '/' + '/'.join(parts[1:(len(parts)-1)]) 
                
                


        else:
            os.system('notify-send Invalid Command')



